### ISSUE TITLE
Getter vs Method

### ISSUE THREAD

**Issue by bmeck** [tc39/proposal-Symbol-description#1]
Is there a reason to use a getter instead of a method? I dont see an example of a getter on a primitive prototype in existing spec.

**Comment by michaelficarra** [comment]
Off the top of my head, `RegExp.prototype.flags` (and each individual flag name) is a getter. I'm sure there's others.

**edit:** And `Object.prototype.__proto__`.

**edit:** `Map.prototype.size`, `Set.prototype.size`, (proposed) `Error.prototype.stack`

**edit:** `%TypedArrayPrototype%.buffer`, `%TypedArrayPrototype%.byteLength`, `%TypedArrayPrototype%.byteOffset`

**Comment by michaelficarra** [comment]
All of these but `__proto__` are "read-only" properties, implemented as a getter without a setter. I think the getter is most appropriate here. Please close if you've been convinced.
