### ISSUE TITLE
stage 3 reviewers

### ISSUE THREAD

**Issue by michaelficarra** [tc39/proposal-Symbol-description#3]
- [x] @ljharb (reviewer)
- [x] @keithamus (reviewer)
- [x] @erights (reviewer)
- [x] @bterlson (still editor for now)

Please let me know once you've reviewed.

**Comment by ljharb** [comment]
Filed #4 to simplify the spec text even further.

**Comment by ljharb** [comment]
Reviewed: the now-3-lines seem good to me.

**Comment by keithamus** [comment]
I've reviewed and am happy with the spec. No issues to report.

**Comment by michaelficarra** [comment]
Ping @erights @bterlson for review.

**Comment by michaelficarra** [comment]
Ping @bterlson @erights one more time for review. I already have sufficient reviews for stage 3, but would like as many as possible.

**Comment by erights** [comment]
Looks Good To Me. +1

**Comment by bterlson** [comment]
Looks good from us! Good luck with Stage 3 :)
