### ISSUE TITLE
test262 tests

### ISSUE THREAD

**Issue by michaelficarra** [tc39/proposal-Symbol-description#5]
Tests should be added to https://github.com/tc39/test262/tree/master/test/built-ins/Symbol

**Comment by gsathya** [comment]
@michaelficarra are you planning on adding test262 tests for this?

@joyeecheung is [implementing](https://chromium-review.googlesource.com/c/v8/v8/+/1088871) this in V8 now and we'd like test262 tests before we ship.

**Comment by michaelficarra** [comment]
Yeah, I had forgotten about this. I'll try to get around to it some time this week. Also, this might be a good opportunity for new contributors.

**Comment by joyeecheung** [comment]
I'd be happy to try working on the tests!

**Comment by michaelficarra** [comment]
@joyeecheung Cool! I am awaiting your PR. Let me know if you need help. Remember to test the missing description case.

**Comment by michaelficarra** [comment]
Fixed by https://github.com/tc39/test262/pull/1590. Thanks @joyeecheung.
