### ISSUE TITLE
What are the use cases?

### ISSUE THREAD

**Issue by not-an-aardvark** [tc39/proposal-Symbol-description#6]
The "goals" section of this proposal says that the goal is to expose the [[Description]] internal slot of a symbol directly, but it doesn't say why that would be useful for developers. It might be useful to give an example of what the `description` field would be used for.

**Comment by michaelficarra** [comment]
See the January 23, 2018 meeting notes: https://github.com/tc39/tc39-notes/blob/master/es8/2018-01/jan-23.md#13iiid-symbolprototypedescription

My initial motivation was for serialisation purposes so I could reconstruct a symbol with the same [[Description]]. There's additional benefit mentioned by Yehuda for debuggers.

Generally, though, if the committee thought it was important enough to be able to give symbols a description, it should be important enough to be able to read that value without jumping through hoops.
